version: "3.0"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: "celery -A config worker -l INFO"
    depends_on:
      - web
      - redis
      - db
    restart: on-failure
    env_file:
      - .env

  celery_beat:
    build: .
    command: > 
      sh -c "python manage.py wait_for_db &&
              celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - web
      - redis
      - db
    restart: on-failure
    env_file:
      - .env

  task_command:
    build: .
    command: sh -c "python manage.py wait_for_db && python manage.py task_command"
    depends_on:
      - web
      - redis
      - db
    restart: no
    env_file:
      - .env

  flower:
    build: .
    ports:
      - "5555:5555"
    command: "celery -A config flower --address=0.0.0.0"
    depends_on:
      - celery
    env_file:
      - .env