# Generated by Django 4.2.2 on 2023-06-16 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kyiv_weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weather",
            options={"verbose_name_plural": "weather"},
        ),
    ]
